# -*-conf-*-

[package]
name = "grido"
version = "0.0.1"
authors = [ "Petr Machata <pmachata@gmail.com>" ]

[[bin]]
name = "grido"

[dependencies]
time = "*"

[dependencies.ncurses]
git = "https://github.com/jeaye/ncurses-rs.git"
